### PR TITLE
updated footer button

### PR DESCRIPTION
**Pull request by schuetta92**
updated footer button to only show hover state when enabled, and made the button look disabled/ not  clickable when disabled.

### CODE REVIEW

**Comment by PWKad** [comment]
Hi @schuetta92 - thanks for this!

Two things - 

1. Can you make sure to sign the CLA?
2. Since this is only changes to 1 file can you squash the commits into a single commit?

Thanks!

**Comment by schuetta92** [comment]
I have signed the CLA, but I signed it again just in case I entered something wrong the first time. 

And I have squashed them into one commit! 

Thanks!

**Comment by PWKad** [comment]
@EisenbergEffect CLA confirmation request

**Comment by EisenbergEffect** [comment]
@PWKad Confirmed.

**Pull request merged**
