### PR TITLE
fix(dialog): Update link to `require`

### PR DESCRIPTION
**Pull request by CharlesPockert**
Update broken `<link>` CSS import to `<require>` as per new framework features/changes

### CODE REVIEW

**Comment by PWKad** [comment]
@EisenbergEffect I assume Mr. Pockert has CLA accepted, double-checking.

**Comment by EisenbergEffect** [comment]
Yes, he's all good to go. FYI I think we need to make some other changes here too. For example, the dialog custom element is actually stomping on the native dialog element. We need to rename our elements so they have ai- as the prefix.

**Comment by PWKad** [comment]
I agree, I think you meant `au` prefix though please confirm and I'll create the PR

**Comment by EisenbergEffect** [comment]
Nope, I meant `ai` as in aurelia-interface.

**Comment by EisenbergEffect** [comment]
New release coming...

**Comment by EisenbergEffect** [comment]
Ok v0.2.1 is out with this PR.

**Pull request merged**
