### PR TITLE
chore(update):

### PR DESCRIPTION
**Pull request by michaelmalonenz**
update to work with the aurelia-framework 0.15.0 release

@PWKad One more issue to make it work with the updated aurelia release - updated the dependencies.  (It's not just cosmetic, it was actually causing issues for me)

### CODE REVIEW

**Comment by PWKad** [comment]
Hey was testing these changes out to see why it was making changes to System.config on the config.js file.  Looks good, re-opening and merging.

**Comment by michaelmalonenz** [comment]
:+1:

**Comment by PWKad** [comment]
If you get a chance can you verify the tests are running for you after the upgrade?  I can't seem to get them to with the newest JSPM.

**Comment by michaelmalonenz** [comment]
Sure, I'll do that now

**Pull request merged**
