### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by RWOverdijk**
Updated dependencies

This was causing forks in my project.

### CODE REVIEW

**Comment by PWKad** [comment]
Can you fix the commit message to match the guidelines?  Something like `chore(deps): update dependencies`

**Comment by RWOverdijk** [comment]
@PWKad Done

**Comment by PWKad** [comment]
@EisenbergEffect CLA confirmation request.

**Comment by EisenbergEffect** [comment]
Confirmed :)

**Comment by RWOverdijk** [comment]
Lot of steps for a simple PR :p

**Comment by EisenbergEffect** [comment]
Apologies @RWOverdijk The process does help us get all our legal ducks in a row, stay organized and have a way to track changes and generate change logs consistently. Once you've done it one time, it's easy afterwards.

**Comment by RWOverdijk** [comment]
I understand. :)

**Pull request merged**
