### PR TITLE
fix(dialog-service): .open() proper error propagation

### PR DESCRIPTION
**Pull request by StrahilKazlachev**
Correcting the promise chain in `.open()` to properly propagate errors.

### CODE REVIEW

**Comment by PWKad** [comment]
@StrahilKazlachev awesome, thanks for this!  Can you give me a brief description of the error this PR fixes along with a quick code sample to reproduce?  Also please make sure if you haven't already to sign the CLA.  Thanks again!

**Comment by StrahilKazlachev** [comment]
@PWKad  `.open()` was just returning the promise that resolves when the controller methods were called(`.ok()`, `.error()`, ...). The promise returned from `_openDialog()` was not chained and in case of errors while creating the VM('incorrect moduleId, errors thrown in the constructor or `.activate()`, ...) were not propagated to the caller of `.open()`. The dialog was never shown but the returned promise is never resolved. Not very brief, sorry. I can make a sample when I get back from work.

**Comment by StrahilKazlachev** [comment]
While I was writing the above I thought that it would be better to `.catch()` in `_openDialog()` and calling `.error()` of the controller, thoughts?
```
function _openDialog(service, childContainer, dialogController) {
  ...
  return _getViewModel(instruction, service.compositionEngine)
    .then(returnedInstruction => {...})
    .catch(e => { dialogController.error(e); });
}
```

**Comment by StrahilKazlachev** [comment]
@PWKad Here is a [sample](https://github.com/StrahilKazlachev/dialog/tree/sample/open/error-propagation). I've modified the dialog sample with 3 cases - incorrect moduleId, error thrown in the VM constructor and error thrown in the `.activate()` method. Check `app.js` what is expected to be logged in the console for every case. Also in the case of error thrown in the `.activate()` method you can see that no dialog is shown but the service `.hasActiveDialog` says `true`.

**Comment by PWKad** [comment]
Seems reasonable to catch the errors.  Going over the sample now, I am trying to verify this doesn't break any currently working functionality.  As a note there don't appear to be any assertions in the unit tests.

**Comment by PWKad** [comment]
I'm good with this @StrahilKazlachev thanks for the contribution.  @EisenbergEffect can you please confirm CLA?

**Comment by EisenbergEffect** [comment]
@PWKad CLA signature is confirmed :)

**Comment by PWKad** [comment]
@StrahilKazlachev let me know what you think about updating the test this way (I know it's brittle but at least we have an assertion in there) - https://github.com/aurelia/dialog/commit/79e39a76067f949a49b30e68bce6aa2570812d4a

**Pull request merged**
