### PR TITLE
Destroy modal only when modalContainer ends its transition

### PR DESCRIPTION
**Pull request by hadrienl**
https://github.com/aurelia/dialog/issues/68

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@PWKad Can you review this real quick?

**Comment by EisenbergEffect** [comment]
Looks good to me. In order for us to accept the PR, you would need to sign our CLA: https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1 Would you mind signing that for me please?

**Comment by EisenbergEffect** [comment]
You will also need to update your commit message, per the commit guidelines.

**Comment by PWKad** [comment]
Sorry I peeked at this before and didn't fully understand the change, sorry to get back to you so late @hadrienl but would it be possible to still ask for an issue logged to identify the problems, preferably with a small representative sample so I can see the behavior and the change?

**Comment by hadrienl** [comment]
https://github.com/aurelia/dialog/issues/68

**Comment by EisenbergEffect** [comment]
@PWKad We have CLA now. Can I go ahead and merge this in for today/tomorrow's releases?

**Pull request merged**
