### PR TITLE
fix(styles): use ux- prefix instead of ai-

### LINKED ISSUE #306: Styles still use old naming "ai-" instead of "ux-"
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.6.1

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Styles still use old naming "ai-" instead of "ux-".
https://github.com/aurelia/dialog/tree/master/styles

**Expected/desired behavior:**
Renaming "ai-" to "ux-" in input.less.

### PR DESCRIPTION
**Pull request by mttmccb**
To close #306

### CODE REVIEW

**Comment by PWKad** [comment]
@StrahilKazlachev this looks good to me can you confirm the thumbs up?

**Comment by StrahilKazlachev** [comment]
@PWKad It seems OK.
My [concerns](https://github.com/aurelia/dialog/issues/306#issuecomment-309983448) stand though. Maintaining multiple sources of the styles is not OK.
- We could add a build step to compile the  `.less`
  - and embed the output in the `.js` file
  - add the compiled `.css` to dist
    - and make users load it
    - we load it somehow
  - ...
- Drop the `.less` file
- ...

**Comment by mttmccb** [comment]
was there a reason the inline styles were favoured rather than requiring a separate css file?

**Comment by StrahilKazlachev** [comment]
I *suppose* zero-config bundling/loading.

**Comment by PWKad** [comment]
Exactly.

**Comment by EisenbergEffect** [comment]
@StrahilKazlachev @PWKad  You are in charge of reviewing and merging for this lib. Just let me know when you are ready for me to make a release and whether or not it's minor or patch. Thanks!

**Comment by StrahilKazlachev** [comment]
OK, so lets merge this after some fixes.
I'll open new issue how we should approach the issues I mentioned above.
@mttmccb could you amend the commit message [accordingly](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md).

**Comment by EisenbergEffect** [comment]
@StrahilKazlachev Where are we at with this? Should we merge this?

**Comment by mttmccb** [comment]
Updated the commit message, finally 😆

**Pull request merged**
