### PR TITLE
refactor(all): pick changes from v1 and refactor build/tests

### LINKED ISSUE #335: Should be based on web standards HTML <dialog> element
Aurelia is forward looking and supports web standards so shouldn't aurelia-dialog be built using the [HTML dialog element](https://www.w3.org/TR/html52/interactive-elements.html#the-dialog-element), be based around that API and use the relevant polyfils to aid with older browsers?

Obviously the API is not as nice as the `aurelia-dialog` API (ie. no async) so it might be worth wrapping it but in Chrome 64 testing [these examples](https://demo.agektmr.com/dialog/) `showModal()` appears to fix #1 (focus issues) and will no doubt be more accessible to screen readers than the current implementation.

### PR DESCRIPTION
**Pull request by bigopon**
- cherry picked changes from @zewa666 for keyboard event type
- cherry picked changes from @timfish for native dialog renderer
- rename default dialog renderer to ux-dialog-renderer (bold file name and class name), still keep old export
- **Breaking change**: modify useRenderer method to accept `'ux' | 'native'` for picking a dialog renderer, instead of asking for impl directly
- modify build to use rollup for all builds, example:
image
- modify typings build: put all in `types` folder. It looks like this
image

- add es2017 dist (not really different from es2015, just consistent with the newer build from other repos)
- use karma + webpack for test instead of requirejs
- remove doc scripts (couldn't figure out why typedoc is upset)

For the breaking change related to `useRenderer`, I think it's a good compromise, (as @3cp would love to say). If folks complain, we can add change it back to:
```ts
  useRenderer(renderer: AbstractRenderer, settings?);
```
from
```ts
  useRenderer(type: 'ux' | 'native', settings?);
```

@EisenbergEffect @RomkeVdMeulen @StrahilKazlachev 

close #335

### CODE REVIEW

**Comment by bigopon** [comment]
CI failing because it can't auto bump the `.rc` version

**Comment by bigopon** [comment]
An update: adjust `useRenderer` interface so that it can have backward compat, while enabling ease of use with bundler/code:

```ts
  useRenderer(renderer: RenderStatic, settings);
```
to
```ts
  useRenderer(renderer: RenderStatic | Promise<RendererStatic> | 'ux' | 'native', settings);
```
We just give 2 string literal values as a hint for what is provided by default. thoughts?

**Comment by bigopon** [comment]
I've update the build so that we now have css in `less` auto built whenever source is built. Also split CSS into its separate chunk so if one prefers not to use default CSS or use native dialog renderer, a lot of unused code can be avoided.

@EisenbergEffect this is ready to go

**Comment by EisenbergEffect** [comment]
As usual, amazing work @bigopon ! I like the api with the string literals for convenience while still enabling custom renderer instances. Nice touch.

**Pull request merged**
