### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gregoryagu**
Changed:

import {DialogService, Prompt} from 'aurelia/modal';

to import {DialogService, Prompt} from 'aurelia-dialog';

### CODE REVIEW

**Comment by gregoryagu** [comment]
Note: This is my first PR.  If I have errored in some way, I apologize in advance.  Just trying to help out a bit with Aurelia.

**Comment by EisenbergEffect** [comment]
@gregoryagu Thanks for the contribution and for reading through the contrib doc. No worries about the incorrect commit format. Now that you know, it will be better for next time.

Speaking of contributing, would you mind signing our CLA please? https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

**Comment by EisenbergEffect** [comment]
@gregoryagu I see a signature that looks like it might be you but needed to confirm.

**Comment by gregoryagu** [comment]
Yes, CLA has been signed.

**Pull request merged**
