### PR TITLE
fix(dialog-controller): remove promise pyramid of doom

### PR DESCRIPTION
**Pull request by sethlivingston**
No issue number, just noticed this got left out from a recent set of commits.

### CODE REVIEW

**Comment by PWKad** [comment]
@sethlivingston if you can squash these commits into one so they all have a valid commit message we can get this merged in.  Also make sure you have signed the CLA.

@EisenbergEffect CLA check.

**Comment by EisenbergEffect** [comment]
@sethlivingston **Thank you for contributing this pull request!** We're truly excited and honored to have you as a member of our community. We look forward to working together with you to further build the Aurelia platform.

We noticed that you haven't yet signed our CLA. We would appreciate it if you would consider doing that for us. Before signing, please take a few minutes to read [our contributing guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md). These guidelines will help get you up to speed on how our community likes to operate and how the pull request process works. Once you have read that, assuming you are in agreement, simply [sign our online CLA](https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1).

After you've signed, please ping this issue to let us know and we'll get your improvements merged in.

Thank you again!
The Aurelia Team

**Comment by EisenbergEffect** [comment]
@sethlivingston We're happy to merge the improvements if you can sign the CLA and please squash the commits. Thanks!

**Comment by sethlivingston** [comment]
Sorry I haven't completed this. I'm going to do this first thing in the
morning!

**Comment by EisenbergEffect** [comment]
No apology necessary. Just wanted to make sure you didn't forget. Thanks for being willing to contribute!

**Comment by sethlivingston** [comment]
@EisenbergEffect sorry I didn't get it merged into a single commit before you merged. I'll make sure it's in correct form next time. :)

**Comment by EisenbergEffect** [comment]
No worries.

**Pull request merged**
