### PR TITLE
docs(hooks): canDeactivate result parameter

### PR DESCRIPTION
**Pull request by pape87**
Add information about the result parameter

Fixes issue: https://github.com/aurelia/dialog/issues/344

### CODE REVIEW

**Comment by Alexander-Taran** [comment]
I'm afraid that won't cut it.
If I remember right deactivate() also receives dialogResult.
And you might want to annotate the code with typing info. 
Last one I'm not sure of. 
Because there is no inheritance.

**Comment by zewa666** [comment]
Right so deactivate takes `result: DialogCloseResult | DialogCloseError`
https://github.com/aurelia/dialog/blob/458477cf7ad3a517280bd97efb62045aa5ea5bba/src/interfaces.ts

This should be updated in the docs PR as well, but I wouldn't annotate any code or so as this is solely a docs PR, so that people reading the documentation immediately figure out there is something passed into the lifecycle hooks.

**Comment by Alexander-Taran** [comment]
@zewa666 agreed. There are interfaces already in place.
https://github.com/aurelia/framework/issues/874#issuecomment-374226001

**Comment by Alexander-Taran** [comment]
PR looks good.
can be merged

**Pull request merged**
