### PR TITLE
fix(lefecycle): handle thrown errors

### PR DESCRIPTION
**Pull request by StrahilKazlachev**
reject the promise chain with the error thrown by the invoked lifecycle method

### CODE REVIEW

**Comment by davismj** [comment]
I'm not sure what to say about this. Was this not working as intended? At first glance, swallowing errors seems like a bad idea.

**Comment by PWKad** [comment]
This doesn't swallow errors, it propagates them back out to the original caller

**Comment by StrahilKazlachev** [comment]
Yes, it propagates them since calling the lefecycle method is done in `.then(() => {...})`. I prefer this to try/catch. I missed this case in my previous PR.

**Comment by CasiOo** [comment]
Will this resolve the issue where you get exception messages such as `h.load() is not a function`?
We experienced the above exception in a CLI project when the view-model existed but the view file had a spelling mistake in the name (it couldn't find the view).

**Comment by StrahilKazlachev** [comment]
@CasiOo I would say no. This should resolve any problems related to `canActivate/canDeactivate/deactivate` throwing an error.

**Pull request merged**
