### PR TITLE
fix(DialogController): fix type definitions for dialog result parameters

### PR DESCRIPTION
**Pull request by richtea**
Modify the aurelia-dialog type definitions file so that it accepts an any parameter instead
of a DialogResult parameter, to correspond with recent changes to DialogController

Fixes issue #110

### CODE REVIEW

**Comment by PWKad** [comment]
Thanks Rich can you sign our CLA?

**Comment by richtea** [comment]
I already did, as rich -at tebb.me.uk, which should be the email address on the commit. Have I boobed?

**Comment by richtea** [comment]
@PWKad I've checked that the commit was made under the correct email address as above, but I can't check that I correctly entered that email in the CLA. If I've got that wrong please advise and I will refile the CLA.

**Comment by PWKad** [comment]
@richtea you are good just wanted to confirm before I @EisenbergEffect for a CLA check

**Comment by EisenbergEffect** [comment]
@PWKad CLA is confirmed :)

**Comment by Gheoan** [comment]
This is already on master https://github.com/aurelia/dialog/blob/master/dist/aurelia-dialog.d.ts#L33.

**Comment by EisenbergEffect** [comment]
@PWKad Can we close this?

**Comment by EisenbergEffect** [comment]
Closing this since the fix was already incorporated.

**Pull request closed without merging**
