### PR TITLE
fix(typings): location of main definition file is incorrect (fixes #279)

### LINKED ISSUE #279: Issue installing typings... status code (404)
Hi guys,
I've a bug when try install a typings.
When execute typings install github:aurelia/dialog displays on console the next message:

typings ERR! message Unable to read typings for "aurelia-dialog". You should check the entry paths in "typings.json" are up to date
typings ERR! caused by https://raw.githubusercontent.com/aurelia/dialog/master/dist/aurelia-dialog.d.ts/index.d.ts responded with 404, expected it to equal 200
typings ERR!
typings ERR! cwd C:\TFS\Architecture\Main\Internationalization\Intricom.Internationalization.Web\Intricom.Internationalization.Web
typings ERR! system Windows_NT 10.0.14393
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aalonso.CONTRIBUCIONS\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "inst
all" "github:aurelia/dialog"
typings ERR! node -v v7.8.0
typings ERR! typings -v 2.1.1
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

Any fix?

Ty

### PR DESCRIPTION
**Pull request by AdamWillden**
Would this fix be sufficient to make this work again (#279)?

### CODE REVIEW

**Comment by StrahilKazlachev** [comment]
Not familiar with typings, but I think it should. @unional can you chime in?
Also as I get it [aurelia-framework](https://github.com/aurelia/dialog/blob/1.0.0-rc.1/src/aurelia-dialog.ts#L5) should be added to the deps list, or not?

**Comment by AdamWillden** [comment]
I couldn't wait as we needed to do a release. I changed the `aurelia-dialog` entry in my typings file to `github:aurelia/dialog/dist/amd/aurelia-dialog.d.ts` thereby circumventing the incorrect typings entry in aurelia-dialog. This confirms to me that the change should work fine.

**Comment by StrahilKazlachev** [comment]
@AdamWillden You've taken care of the braking changes also, that's fast.

**Comment by unional** [comment]
Seems like the project does not create `dist/aurelia-dialog.d.ts` anymore so the path should be updated. 

However I would update to the commonjs path to match what's in `package.json` 

Also, nowadays you probably should be using typescript 2+ and you don't need `typings` for `aurelia` packages anymore.

**Comment by AdamWillden** [comment]
I have updated to use the `commonjs` path as per the suggestion by @unional. I've not tested it.

@StrahilKazlachev the breaking changes for aurelia-dialog were very simple to accommodate 👍 

@unional using JSPM I found I still needed to add typings... would be nice if I could do away with having to manage them.

**Comment by StrahilKazlachev** [comment]
@AdamWillden Sorry to bother but could you [sign our CLA](https://docs.google.com/forms/d/e/1FAIpQLSfxeVR6QsX3il0mrbn12c_qOS2KbOEzp2Djr9sUHKlsABqZPg/viewform?c=0&w=1).

**Comment by unional** [comment]
@AdamWillden yeah, that's why I added `jspm` support to `typings`.

**Comment by AdamWillden** [comment]
@StrahilKazlachev I'm sure I already have, no?

**Comment by StrahilKazlachev** [comment]
@AdamWillden If so, sorry to bother. The CircleCI check seems to be on hiatus, a-a-a-and I went and merged without noticing.

**Comment by AdamWillden** [comment]
@StrahilKazlachev no stress - I filled it out again to be sure :-)

**Pull request merged**
