### PR TITLE
Renderer bug fixes - scrolling and close behavior

### LINKED ISSUE #125: Dialog doesn't close on click out
Hi, according to the docs (and the source), if `setting.lock = false` and the user clicks outside of the dialog, it will close it and resolve it with cancel. But, when I click outside - nothing happens.

The event handler, for closing the dialog, is set on the overlay layer (https://github.com/aurelia/dialog/blob/master/src/renderers/dialog-renderer.js#L76) and is never called, because `ai-dialog-overlay` has css style `pointer-events:none`, which prevents all clicks on this element. 

I found this issue #74, which describes the same problem about closing the dialog, but the problem were that the container was on top of the overlay and it was fixed with disabling pointer events on the `ai-dialog-container` to enable click events on `ai-dialog-overlay` #79

When I remove `pointer-events:none`; from `ai-dialog-overlay` and set it on `ai-dialog-container` the event handler is called and the dialog is closed correctly.

### PR DESCRIPTION
**Pull request by jedd-ahyoung**
Fixes #125, #103, and #128.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Awesome. @PWKad Can you review this. I like to always have a second team member review if possible. @jedd-ahyoung If Patrick approves, then go ahead and merge. Ping me after the merge. Keep me posted on all the updates so I can do a new release when things are ready.

**Comment by jedd-ahyoung** [comment]
So I had to hack something together - there's a CSS way to get the overlay click working, but it doesn't work if you want to be able to scroll the modal window. As such, I defaulted to doing an "event.stopPropagation" on the ai-dialog element. However, I just realized - I don't know if this will cause problems with event.delegate functions in Aurelia, as they might need to bubble back up to the root element....

**Comment by EisenbergEffect** [comment]
Yes, that would cause an issue. There might be a way around it though using
DOM boundaries. It's something we added for shadow DOM that might work here
too.

**Comment by jedd-ahyoung** [comment]
After having looked into this problem, I think that the DOM boundary solution will work - but due to how the renderer and the service interact (and how the view is structured), I think that this solution will require a refactor of the default renderer component. This needs to happen anyway as the thing is pretty buggy as-is. (I believe that using transient renderers instead of a singleton will simplify everything and remove a lot of bugs.)

I can do this but I don't have immediate time. How quickly would you like a fix for this? If necessary, we can hack a patch together for a quick release and do a full refactor later. Let me know.

**Comment by EisenbergEffect** [comment]
Give me an ETA and we can make a decision based on that. I don't see any issues with making the render transient. That seems to make sense, esp. if you want to be able to specify a per instance renderer in the future.

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect I authored https://github.com/aurelia/dialog/pull/143 on Saturday while en route back to Tallahassee. If that's accepted, I can rebase this change onto master and find a solution for the click issue.

**Comment by PWKad** [comment]
This lgtm

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung Where are we at with this?

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect I've just forced pushed this branch with updates. I solved the overlay issue by monkey-patching the event and checking for the property duing the bubble phase. Tests are passing and this can be merged after it's rebased onto the other refactor PR.

**Pull request merged**
