### PR TITLE
Webpack docs, regex for windows

### PR DESCRIPTION
**Pull request by valichek**
Fix regex according to https://github.com/aurelia/dialog/issues/127#issuecomment-220803355

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung Please merge.

**Comment by EisenbergEffect** [comment]
@niieani Can you review this based on your Webpack knowledge?

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect @niieani I'm going to go ahead and merge this PR. If there are issues with the documentation, they can be addressed in a separate request.

**Comment by niieani** [comment]
OK. In fact, this configuration won't be at all necessary when the new Webpack plugin is merged.

**Pull request merged**
