### PR TITLE
fix: fix umd build browser compatibility

### PR DESCRIPTION
**Pull request by huochunpeng**
closes aurelia/cli#1033

### CODE REVIEW

**Comment by huochunpeng** [comment]
@fkleuver workflow not ready? 😄

**Comment by fkleuver** [comment]
Looks like this repo is not ready. Can we make `develop` the merge target?

**Comment by huochunpeng** [comment]
Sh*t, you see what happened after I switch to develop branch.
This repo's master has a big diff with v2.x.

**Comment by bigopon** [comment]
These following 3 fields are troublesome
```json
  "module": "dist/es2015/aurelia-dialog.js",
  "browser": "dist/umd/aurelia-dialog.js",
  "unpkg": "dist/umd/aurelia-dialog.js",
```
We need an additional distribution: `umd-es2015` and point unpkg to that. and we change umd distribution to umd module format + es5

**Comment by huochunpeng** [comment]
close in favour of #369.

**Pull request closed without merging**
